markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://yyzs.github.io
author: yyzs
email: elevendivide@gmail.com
name: yyzs's Homepage
github: yyzs
pygments: true
safe: true
paginate: 16
auto: true

